# This is a -*- Makefile -*-

ifeq ($(TARGET), redbee-econotag)
CFLAGS += -DSHA2_USE_INTTYPES_H=1 -DLITTLE_ENDIAN=3412 -DBYTE_ORDER=LITTLE_ENDIAN
endif

ifeq ($(TARGET), native)
CFLAGS += -DSHA2_USE_INTTYPES_H=1
endif

ifeq ($(TARGET), minimal-net)
CFLAGS += -DSHA2_USE_INTTYPES_H=1
endif

CFLAGS += -DDTLSv12 -DWITH_SHA256 

tinydtls_src = dtls.c crypto.c hmac.c rijndael.c sha2.c ccm.c netq.c debug.c ecc.c dtls_time.c peer.c
