# This is a -*- Makefile -*-

#dtls_src = peer.c dtls.c crypto.c ccm.c hmac.c debug.c \
#  aes/rijndael.c sha2/sha2.c

ifeq ($(TARGET), redbee-econotag)
CFLAGS += -DSHA2_USE_INTTYPES_H=1 -DLITTLE_ENDIAN=3412 -DBYTE_ORDER=LITTLE_ENDIAN
endif

#CFLAGS += -DDTLSv12 -DWITH_SHA256 
CFLAGS += -DWITH_SHA1 -DWITH_MD5

dtls_src = dtls.c crypto.c hmac.c debug.c rijndael.c sha2.c sha1.c md5.c

